name: sih_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  latlong2: ^0.9.0
  flutter_map: ^6.1.0
  shared_preferences: ^2.2.2
  provider:
  flutter_tts: ^3.6.3
  socket_io_client: ^1.0.2
  url_launcher: ^6.2.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
